//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestApp.Resource.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while Activating/De-Activating Contact..
        /// </summary>
        public static string ActivationIssueMessage {
            get {
                return ResourceManager.GetString("ActivationIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added In.
        /// </summary>
        public static string AddedIn {
            get {
                return ResourceManager.GetString("AddedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact for Action.
        /// </summary>
        public static string ContactActionInvalidMessage {
            get {
                return ResourceManager.GetString("ContactActionInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while taking action on Contact.
        /// </summary>
        public static string ContactActionIssueMessage {
            get {
                return ResourceManager.GetString("ContactActionIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while deleting contact details.
        /// </summary>
        public static string ContactDeleteFailMessage {
            get {
                return ResourceManager.GetString("ContactDeleteFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact deleted successfully.
        /// </summary>
        public static string ContactDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("ContactDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Already Exist.
        /// </summary>
        public static string ContactExistMessage {
            get {
                return ResourceManager.GetString("ContactExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while fetching contact details.
        /// </summary>
        public static string ContactListFetchIssueMessage {
            get {
                return ResourceManager.GetString("ContactListFetchIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact details fetched successfully.
        /// </summary>
        public static string ContactListFetchSuccessMessage {
            get {
                return ResourceManager.GetString("ContactListFetchSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Management.
        /// </summary>
        public static string ContactManagement {
            get {
                return ResourceManager.GetString("ContactManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        public static string ContactNumber {
            get {
                return ResourceManager.GetString("ContactNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue while Adding Contact Details.
        /// </summary>
        public static string ContactSaveIssueMessage {
            get {
                return ResourceManager.GetString("ContactSaveIssueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Details saved successfully.
        /// </summary>
        public static string ContactSaveSuccessMessage {
            get {
                return ResourceManager.GetString("ContactSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-activated.
        /// </summary>
        public static string DeActivated {
            get {
                return ResourceManager.GetString("DeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId Already Exist.
        /// </summary>
        public static string EmailExistMessage {
            get {
                return ResourceManager.GetString("EmailExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite.
        /// </summary>
        public static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite List.
        /// </summary>
        public static string FavouriteList {
            get {
                return ResourceManager.GetString("FavouriteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact Details.
        /// </summary>
        public static string InvalidContactDetailMessage {
            get {
                return ResourceManager.GetString("InvalidContactDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact for Activation/De-activation.
        /// </summary>
        public static string InvalidContactMessage {
            get {
                return ResourceManager.GetString("InvalidContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Contact selected.
        /// </summary>
        public static string InvalidContactSelected {
            get {
                return ResourceManager.GetString("InvalidContactSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileNo Already Exist.
        /// </summary>
        public static string MobileNoExistMessage {
            get {
                return ResourceManager.GetString("MobileNoExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact Selected.
        /// </summary>
        public static string NoContactSelected {
            get {
                return ResourceManager.GetString("NoContactSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed From.
        /// </summary>
        public static string RemovedFrom {
            get {
                return ResourceManager.GetString("RemovedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Contact no, First Name or Last Name.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Went Wrong.
        /// </summary>
        public static string SomethingWentWrongMessage {
            get {
                return ResourceManager.GetString("SomethingWentWrongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Contacts.
        /// </summary>
        public static string TotalContacts {
            get {
                return ResourceManager.GetString("TotalContacts", resourceCulture);
            }
        }
    }
}
